name = "Sophon"
uuid = "077df616-1c15-4d29-b519-7542a62df138"
authors = ["YichengDWu <yicheng.wu@ucalgary.ca> and contributors"]
version = "0.4.4"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NNlibCUDA = "a00861dc-f156-4864-bf3c-e6376f28a68d"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[weakdeps]
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
TaylorDiff = "b36ab563-344f-407b-a36a-4f200bebf99c"

[extensions]
SophonOptimisersExt = "Optimisers"
SophonTaylorDiffExt = "TaylorDiff"

[compat]
Adapt = "3"
CUDA = "3, 4, 5"
ChainRulesCore = "1"
ComponentArrays = "0.15"
Distributions = "0.25"
DomainSets = "0.5, 0.6"
ForwardDiff = "0.10"
GPUArrays = "8"
GPUArraysCore = "0.1"
LRUCache = "1"
Lux = "0.5.6"
MacroTools = "0.5"
Memoize = "0.4"
ModelingToolkit = "8"
NNlib = "0.8"
NNlibCUDA = "0.2"
Optimisers = "0.2"
Optimization = "3"
OptimizationOptimisers = "0.1"
QuasiMonteCarlo = "0.2, 0.3"
Requires = "1"
RuntimeGeneratedFunctions = "0.5"
SciMLBase = "1"
Sobol = "1, 2"
StaticArrays = "1.5"
StaticArraysCore = "1"
StatsBase = "0.33, 0.34"
Symbolics = "4, 5"
julia = "1.8"

[extras]
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
TaylorDiff = "b36ab563-344f-407b-a36a-4f200bebf99c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Zygote", "ModelingToolkit", "DomainSets", "OptimizationOptimJL", "TaylorDiff"]
